
services:
  api:
    image: abudev22/devops-api::v3
    ports:
      - "8002:8000"
    #command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - my-postgres
   
  my-postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_PASSWORD=postgres"
   

volumes:
  postgres_data:




































